### ISSUE TITLE
Cannot find first rank?

### ISSUE THREAD

**Issue by CarThax08** [okx-code/Rankup3#31]
So... I didn't even change the first rankup and it's broken. It tells me to look in the console so I did. It told me that it cannot load the first rank. If you need the rankups file, I can send it to you.
(Error text is:
20.03 20:49:12 [Server] WARN java.lang.IllegalArgumentException: Could not find a first rank. First ranks must not have anything that ranks up to them.
20.03 20:49:12 [Server] WARN at sh.okx.rankup.RankList.getFirst(RankList.java:62)
20.03 20:49:12 [Server] WARN at sh.okx.rankup.RankList.getOrderedList(RankList.java:67)
20.03 20:49:12 [Server] WARN at sh.okx.rankup.Rankup.refreshRanks(Rankup.java:260)
20.03 20:49:12 [Server] WARN at sh.okx.rankup.Rankup.lambda$loadConfigs$3(Rankup.java:245)
20.03 20:49:12 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
20.03 20:49:12 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
20.03 20:49:12 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
20.03 20:49:12 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
20.03 20:49:12 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
20.03 20:49:12 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
20.03 20:49:12 [Server] WARN at java.lang.Thread.run(Thread.java:748)
20.03 20:49:12 [Server] ERROR [Rankup] Failed to load Rankup
20.03 20:49:12 [Server] ERROR [Rankup] Could not find a first rank. First ranks must not have anything that ranks up to them.)

**Comment by okx-code** [comment]
I'll need your rankups.yml

**Comment by CarThax08** [comment]
should I send it as a .txt?
It would let me send the .yml

**Comment by CarThax08** [comment]
# see https://github.com/okx-code/Rankup3/wiki/Rank-format      

# this name doesn't matter
Aexample:
  # the name of the group
  # players have to be in this rank to rankup
  rank: 'A'
  # the name of the rank a player can rankup to
  next: 'B'
  # List of requirements to go to the next rank
  # This example will charge 1000 money to rankup from A to B.
  # https://github.com/okx-code/Rankup3/wiki/Requirements
  # custom requirements can also be added by other plugins.
  requirements:
    - 'money 20000'
  # the console will run these commands when a player ranks up
  # nb: groups are automatically changed with vault
  #commands:
  # this will run when a player ranks up from A to B.
  #- 'say {PLAYER} well done for ranking up from {OLD_RANK} to {RANK}!'
Bexample:
  rank: 'B'
  next: 'C'
  requirements:
    - 'money 50000'
Cexample:
  rank: 'C'
  next: 'D'
  requirements:
    - 'money 100000'
Dexample
  rank: 'D'
  next: 'E'
  requirements:
    - 'money 500000'
  # you can have a custom messages for each rank
  # the paths of these messages are the same as in the messages for your locale
  rankup:
    requirements-not-met: '&cYou need 5000 money and 2 levels of XP to rankup to D.'
    list:
      complete: "&7{OLD_RANK} &8\xbb &7{RANK} &e(5000 money, 2 XP levels)"
      current: "&c{OLD_RANK} &e\xbb &c{RANK} &e(5000 money, 2 XP levels)"
      incomplete: "&r{OLD_RANK} &e\xbb &r{RANK} &e(5000 money, 2 XP levels)"

**Comment by CarThax08** [comment]
I tried ctrl + c and ctrl + v

**Comment by CarThax08** [comment]
[rankups.yml.txt](https://github.com/okx-code/Rankup3/files/4362240/rankups.yml.txt)
Here is the .txt if you need it.

**Comment by CarThax08** [comment]
Was .yml. I just changed it to .txt via notepad

**Comment by okx-code** [comment]
You missed a colon after Dexample. You also seem to have missed this error in console, which would've helped you fix the issue:

```
[01:00:51 ERROR]: Cannot load plugins/Rankup/rankups.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
 in 'string', line 31, column 1:
    Dexample
    ^
could not find expected ':'
 in 'string', line 32, column 7:
      rank: 'D'
          ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[patched_1.15.2.jar:git-Paper-76]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.15.2.jar:git-Paper-76]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.15.2.jar:git-Paper-76]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) ~[patched_1.15.2.jar:git-Paper-76]
        at sh.okx.rankup.Rankup.loadConfig(Rankup.java:297) ~[?:?]
        at sh.okx.rankup.Rankup.refreshRanks(Rankup.java:259) ~[?:?]
        at sh.okx.rankup.Rankup.lambda$loadConfigs$3(Rankup.java:246) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-76]        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-76]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-76]        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:423) ~[patched_1.15.2.jar:git-Paper-76]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-76]        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-76]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
 in 'string', line 31, column 1:
    Dexample
    ^
could not find expected ':'
 in 'string', line 32, column 7:
      rank: 'D'
          ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:464) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:278) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:504) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceFirstEntry.produce(ParserImpl.java:496) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:190) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:142) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:239) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:230) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:218) ~[patched_1.15.2.jar:git-Paper-76]        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:239) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:230) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:218) ~[patched_1.15.2.jar:git-Paper-76]        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525) ~[patched_1.15.2.jar:git-Paper-76]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:438) ~[patched_1.15.2.jar:git-Paper-76]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[patched_1.15.2.jar:git-Paper-76]
        ... 13 more
```
