### ISSUE TITLE
Trying to use PlaceholderAPI placeholders gives internal server error

### ISSUE THREAD

**Issue by HewloThere** [okx-code/Rankup3#4]
Hi,

I would just like to report an error when trying to use PlaceholderAPI placeholders.

Error:
```
[02:29:33 INFO]: HewloThere issued server command: /papi parse HewloThere %rankup_percent_left%
[02:29:33 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.9.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-401]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-401]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729) ~[patched_1.13.2.jar:git-Paper-401]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1757) ~[patched_1.13.2.jar:git-Paper-401]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1561) ~[patched_1.13.2.jar:git-Paper-401]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-401]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-401]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-401]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-401]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-401]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-401]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-401]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-401]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at sh.okx.rankup.RankList.next(RankList.java:67) ~[?:?]
        at sh.okx.rankup.placeholders.RankupExpansion.onPlaceholderRequest(RankupExpansion.java:36) ~[?:?]
        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:237) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:205) ~[?:?]
        at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:186) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-401]
        ... 15 more
```

Paper: git-Paper-401 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
PAPI version: 2.9.2
Rankup3 version: 3.2

Edit:
List of plugins
```
Plugins (28): BossShopPro, CoreProtect, CraftBook, CrateReloaded, DeluxeChat, DeluxeJoin, Essentials*, EssentialsGUI*, EssentialsSpawn*, Factions, ItemShops*, Jobs, LiteBans, LuckPerms*, mcMMO, McMMORewards*, Multiverse-Core*, MysqlEcoBridge*, OpenInv*, PlaceholderAPI, ProtocolLib*, RandomTeleport*, SilkSpawners, TitleManager*, Vault*, Votifier, WorldEdit, WorldGuard
```

**Comment by okx-code** [comment]
Could I see your rankups.yml too?

**Comment by HewloThere** [comment]
rankups.yml:

```yaml
A:
  rank: 'a'
  next: 'B'
  requirements:
    money: 3000
  operation: all
B:
  rank: 'b'
  next: 'C'
  requirements:
    money: 8000
  operation: all
C:
  rank: 'c'
  next: 'D'
  requirements:
    money: 15000
  operation: all
D:
  rank: 'd'
  next: 'E'
  requirements:
    money: 25000
  operation: all
E:
  rank: 'e'
  next: 'F'
  requirements:
    money: 40000
  operation: all
F:
  rank: 'f'
  next: 'G'
  requirements:
    money: 75000
  operation: all
G:
  rank: 'g'
  next: 'H'
  requirements:
    money: 125000
  operation: all
H:
  rank: 'h'
  next: 'I'
  requirements:
    money: 200000
  operation: all
I:
  rank: 'i'
  next: 'J'
  requirements:
    money: 300000
  operation: all
J:
  rank: 'j'
  next: 'K'
  requirements:
    money: 500000
  operation: all
K:
  rank: 'k'
  next: 'L'
  requirements:
    money: 750000
  operation: all
L:
  rank: 'l'
  next: 'M'
  requirements:
    money: 1050000
  operation: all
M:
  rank: 'm'
  next: 'N'
  requirements:
    money: 1350000
  operation: all
N:
  rank: 'n'
  next: 'O'
  requirements:
    money: 1700000
  operation: all
O:
  rank: 'o'
  next: 'P'
  requirements:
    money: 2200000
  operation: all
P:
  rank: 'p'
  next: 'Q'
  requirements:
    money: 2800000
  operation: all
Q:
  rank: 'q'
  next: 'R'
  requirements:
    money: 3500000
  operation: all
R:
  rank: 'r'
  next: 'S'
  requirements:
    money: 5000000
  operation: all
S:
  rank: 's'
  next: 'T'
  requirements:
    money: 10000000
  operation: all
T:
  rank: 't'
  next: 'U'
  requirements:
    money: 25000000
  operation: all
U:
  rank: 'u'
  next: 'V'
  requirements:
    money: 50000000
  operation: all
V:
  rank: 'v'
  next: 'W'
  requirements:
    money: 100000000
  operation: all
W:
  rank: 'w'
  next: 'X'
  requirements:
    money: 250000000
  operation: all
X:
  rank: 'x'
  next: 'Y'
  requirements:
    money: 500000000
  operation: all
Y:
  rank: 'y'
  next: 'Z'
  requirements:
    money: 1000000000
  operation: all
Z:
  rank: 'z'
  requirements:
    money: 10000000000
  operation: all
```

prestige.yml:
```yaml
# first:
#   # the rank people must be to use this prestige
#   from: 'D'
#   # the rank to change it to
#   to: 'A'
#   next: 'P1example'
#   # see rankups.yml for more information on requirements, operations, commands and messages
#   requirements:
#     money: 10000
#   # optional, defaults to all
#   operation: all
# P1example:
#   from: 'D'
#   to: 'A'
#   # the rank add to indicate this prestige
#   rank: 'P1'
#   next: 'P2example'
#   requirements:
#     money: 20000
#     xp-level: 5
# P2example:
#   from: 'D'
#   to: 'A'
#   rank: 'P2'
```

config.yml:

```yaml
# this is used for letting you know that you need to update/change your config file
version: 1

# whether /ranks and /prestiges should be enabled (true) or disabled (false)
# /rankup3 reload will not do anything if this is changed,
# you will have to restart your server.
ranks: true
# you can alternatively negate the permission rankup.prestiges
# this will also make the command not autocomplete in 1.13
prestiges: true

# whether or not /prestige and /prestiges should be enabled.
# you can alternatively negate the permission rankup.prestige
# this will also make the command not autocomplete in 1.13
prestige: true

# how people should confirm ranking up
# options are: gui, text or none
confirmation-type: 'text'

# how long in seconds people have to wait between a /rankup and a /prestige
# only successful rankups and prestiges start the cooldown.
# set to 0 to disable.
cooldown: 0

gui:
  rows: 1
  rankup:
    material: EMERALD_BLOCK
    # index can be separated by spaces to show in multiple ways
    # ie, 0-3 9-12 18-21
    # you can also just use a single number instead of a range.
    index: 0-3
    name: '&a&lConfirm'
    # lore is optional
    lore: '&6Rankup to &b{RANK}'
  cancel:
    material: REDSTONE_BLOCK
    index: 5-8
    name: '&c&lCancel'
  fill:
    name: ' '
    # if you are using a 1.8-1.12 and you want to change this
    # you can use MATERIAL:data, for example STAINED_GLASS_PANE:8
    # this works for both the rankup and cancel blocks as well
    material: BLACK_STAINED_GLASS_PANE

text:
  # the time in seconds for a player to
  # confirm by typing /rankup again
  timeout: 10

placeholders:
  # format for money. for more information, see
  # https://docs.oracle.com/javase/8/docs/api/java/text/DecimalFormat.html
  money-format: "#,##0.##"
  percent-format: "0.##"
  # the format used for requirements
  simple-format: "#.##"
  # used for current_rank and next_rank placeholders when a player is not in anything in rankups.yml
  not-in-ladder: "None"
  # used in next_rank placeholders when there is no rankup
  highest-rank: "Z"
  # used in /prestiges as the {OLD_RANK} placeholder for the first prestige rank
  first-prestige-rank: 'D'

# what to shorten money by.
# ie 1000 -> 1k
# set to an empty list to disable
shorten:
- 'k'
- 'M'
- 'B'
- 'T'
- 'Q'
- 'Qu'
- 'S'
```

**Comment by HewloThere** [comment]
Just wanted to add, tried the 3.2.1 version you posted in #pre-releases on discord and still doesn't work. Getting the **exact** same error. the only difference was the time. :P

**Comment by okx-code** [comment]
In
```yaml
Z:
  rank: 'z'
  requirements:
    money: 10000000000
  operation: all
```
Only include the `rank` part.

**Comment by HewloThere** [comment]
It worked after at least un commenting the prestige.yml fine and with your fix too.
