### ISSUE TITLE
Rankup 3.10 does the /rankup command fails

### ISSUE THREAD

**Issue by BurkenDev** [okx-code/Rankup3#47]
In rankup 3.10 the /rankup command fails with an error. In Rankup-3.9 it works perfectly.

Unloading 3.10 and loading 3.9 works great, the reverse does not. Nor does restarting the server.

This is the error:

>.... [17:41:12 WARN]: [Rankup] Task #325 for Rankup v3.10 generated an exception
java.lang.NoClassDefFoundError: com/bencodez/votingplugin/user/UserManager
at sh.okx.rankup.requirements.requirement.votingplugin.VotingPluginVotesRequirement.getProgress(VotingPluginVotesRequirement.java:21) ~[?:?]
at sh.okx.rankup.requirements.ProgressiveRequirement.getRemaining(ProgressiveRequirement.java:30) ~[?:?]
at sh.okx.rankup.requirements.ProgressiveRequirement.getRemaining(ProgressiveRequirement.java:26) ~[?:?]
at sh.okx.rankup.requirements.ProgressiveRequirement.check(ProgressiveRequirement.java:21) ~[?:?]
at sh.okx.rankup.ranks.requirements.ListRankRequirements.hasRequirements(ListRankRequirements.java:23) ~[?:?]
at sh.okx.rankup.ranks.Rank.hasRequirements(Rank.java:37) ~[?:?]
at sh.okx.rankup.RankupHelper.checkRankup(RankupHelper.java:159) ~[?:?]
at sh.okx.rankup.AutoRankup.run(AutoRankup.java:21) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-291]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-291]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by okx-code** [comment]
Update your version of VotingPlugin

**Comment by BurkenDev** [comment]
Sorry but it's the latest VotingPlugin version too.

**Comment by okx-code** [comment]
Can you reply with which version it is?
