### ISSUE TITLE
Rankup3 Error GUI

### ISSUE THREAD

**Issue by TheCiROMG** [okx-code/Rankup3#51]
[19:11:50 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ranks' in plugin Rankup v3.10
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-337]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-337]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2011) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1822) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1775) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-337]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-337]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.NullPointerException
        at sh.okx.rankup.gui.Gui.getItem(Gui.java:78) ~[?:?]
        at sh.okx.rankup.ranksgui.RanksGui.lambda$open$0(RanksGui.java:43) ~[?:?]
        at sh.okx.rankup.ranksgui.RanksGui.get(RanksGui.java:92) ~[?:?]
        at sh.okx.rankup.ranksgui.RanksGui.open(RanksGui.java:43) ~[?:?]
        at sh.okx.rankup.ranksgui.RanksGuiListener.open(RanksGuiListener.java:45) ~[?:?]
        at sh.okx.rankup.ranksgui.RanksGuiCommand.onCommand(RanksGuiCommand.java:23) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-337]
        ... 19 more

user running /ranks (with gui enabled in config.yml) gets that error

**Comment by okx-code** [comment]
You can ask for support on the discord server: https://discord.gg/maB4382
