### ISSUE TITLE
Rankup Could not find a first rank. First ranks must not have anything that ranks up to them. Error.

### ISSUE THREAD

**Issue by AspectPower** [okx-code/Rankup3#69]
[18:11:47 WARN]: java.lang.IllegalArgumentException: Could not find a first rank. First ranks must not have anything that ranks up to them.>
[18:11:47 WARN]: 	at Rankup-3.6.1.jar//sh.okx.rankup.RankList.getFirst(RankList.java:62)>
[18:11:47 WARN]: 	at Rankup-3.6.1.jar//sh.okx.rankup.RankList.getOrderedList(RankList.java:67)>
[18:11:47 WARN]: 	at Rankup-3.6.1.jar//sh.okx.rankup.Rankup.refreshRanks(Rankup.java:260)>
[18:11:47 WARN]: 	at Rankup-3.6.1.jar//sh.okx.rankup.Rankup.lambda$loadConfigs$3(Rankup.java:245)>
[18:11:47 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)>
[18:11:47 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)>
[18:11:47 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1229)>
[18:11:47 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)>
[18:11:47 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)>
[18:11:47 ERROR]: [Rankup] Failed to load Rankup>
[18:11:47 ERROR]: [Rankup] Could not find a first rank. First ranks must not have anything that ranks up to them
This is the console, can anyone help me fix this?

**Comment by NicBOMB** [comment]
> [18:11:47 WARN]: java.lang.IllegalArgumentException: Could not find a first rank. First ranks must not have anything that ranks up to them.> [18:11:47 WARN]: at Rankup-3.6.1.jar//sh.okx.rankup.RankList.getFirst(RankList.java:62)> [18:11:47 WARN]: at Rankup-3.6.1.jar//sh.okx.rankup.RankList.getOrderedList(RankList.java:67)> [18:11:47 WARN]: at Rankup-3.6.1.jar//sh.okx.rankup.Rankup.refreshRanks(Rankup.java:260)> [18:11:47 WARN]: at Rankup-3.6.1.jar//sh.okx.rankup.Rankup.lambda$loadConfigs$3(Rankup.java:245)> [18:11:47 WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)> [18:11:47 WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)> [18:11:47 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1229)> [18:11:47 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)> [18:11:47 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)> [18:11:47 ERROR]: [Rankup] Failed to load Rankup> [18:11:47 ERROR]: [Rankup] Could not find a first rank. First ranks must not have anything that ranks up to them This is the console, can anyone help me fix this?

Your version of Rankup is out of date. Please update before making an issue. You can find the latest version here https://www.spigotmc.org/resources/rankup.76964/ . You can also read the wiki at https://okx.sh/rankup/ for more information.

**Comment by AspectPower** [comment]
İ updated my rankup and this is the error.
 Cannot load plugins/Rankup/rankups.yml>
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 9, column 1:
    Oyuncu:
    ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 45, column 2:
     Elmas:
     ^
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[server.jar:git-Paper-388]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[server.jar:git-Paper-388]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[server.jar:git-Paper-388]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:188) ~[server.jar:git-Paper-388]
	at sh.okx.rankup.RankupPlugin.loadRankupConfig(RankupPlugin.java:367) ~[Rankup-3.13.1.jar:?]
	at sh.okx.rankup.RankupPlugin.refreshRanks(RankupPlugin.java:324) ~[Rankup-3.13.1.jar:?]
	at sh.okx.rankup.RankupPlugin.lambda$loadConfigs$6(RankupPlugin.java:304) ~[Rankup-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[server.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[server.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[server.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[server.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 9, column 1:
    Oyuncu:
    ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 45, column 2:
     Elmas:
     ^
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:617) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:292) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[server.jar:git-Paper-388]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[server.jar:git-Paper-388]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[server.jar:git-Paper-388]
