### ISSUE TITLE
Null pointer exception in locale {AMOUNT votingplugin-votes} 

### ISSUE THREAD

**Issue by kalleswe** [okx-code/Rankup3#80]
Requirement votingplugin-votes now works when specified in the rankups.yml, but not when specified {AMOUNT votingplugin-votes} in the locale file.

[19:05:42] [Server thread/INFO]: user issued server command: /ranks
[19:05:42] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ranks' in plugin Rankup v3.14.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991) ~[paper-1.20.2.jar:git-Paper-297]
        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.2.jar:git-Paper-297]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2208) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2168) ~[
?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-297]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: sh.okx.rankup.messages.pebble.InvalidRequirementException: Invalid requirement: votingplugin-votes for rank default
        at sh.okx.rankup.messages.pebble.RankContext.getRequirement(RankContext.java:33) ~[Rankup-3.14.4.jar:?]
        at sh.okx.rankup.messages.pebble.RankContext.getReq(RankContext.java:43) ~[Rankup-3.14.4.jar:?]
        at sh.okx.rankup.text.LegacyTextProcessor.lambda$replacePlaceholder$6(LegacyTextProcessor.java:73) ~[Rankup-3.14.4.jar:?]
        at sh.okx.rankup.text.LegacyTextProcessor.get(LegacyTextProcessor.java:104) ~[Rankup-3.14.4.jar:?]
        at sh.okx.rankup.text.LegacyTextProcessor.replacePlaceholder(LegacyTextProcessor.java:72) ~[Rankup-3.14.4.jar:?]
        at sh.okx.rankup.text.LegacyTextProcessor.process(LegacyTextProcessor.java:40) ~[Rankup-3.14.4.jar:?]
        at sh.okx.rankup.text.ChainedTextProcessor.process(ChainedTextProcessor.java:13) ~[Rankup-3.14.4.jar:?]
        at sh.okx.rankup.messages.pebble.PebbleMessageBuilder.toString(PebbleMessageBuilder.java:106) ~[Rankup-3.14.4.jar:?]
        at sh.okx.rankup.gui.Gui.format(Gui.java:144) ~[Rankup-3.14.4.jar:?]
        at sh.okx.rankup.gui.Gui.getItem(Gui.java:126) ~[Rankup-3.14.4.jar:?]
        at sh.okx.rankup.gui.Gui.getItem(Gui.java:89) ~[Rankup-3.14.4.jar:?]
        at sh.okx.rankup.ranksgui.RanksGui.lambda$open$1(RanksGui.java:65) ~[Rankup-3.14.4.jar:?]
        at sh.okx.rankup.ranksgui.RanksGui.get(RanksGui.java:94) ~[Rankup-3.14.4.jar:?]
        at sh.okx.rankup.ranksgui.RanksGui.open(RanksGui.java:65) ~[Rankup-3.14.4.jar:?]
        at sh.okx.rankup.ranksgui.RanksGuiListener.open(RanksGuiListener.java:45) ~[Rankup-3.14.4.jar:?]
        at sh.okx.rankup.ranksgui.RanksGuiCommand.onCommand(RanksGuiCommand.java:26) ~[Rankup-3.14.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more

**Comment by okx-code** [comment]
Hello, for support please join the discord: https://discord.gg/maB4382

There is not enough information here to diagnose this as a bug.
